# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e481fcae35370bb334275810bf00ab6b7524b480993aa178dce40bccabfa35c317e9cea0e3b76f4b4ed7fff91d01deb29532c1988008d31a5cc1461d6108f61

test:
  secret_key_base: b3b7a47dd7795412fbf57fa61d6709b8b804057e4b293e3e776bf519ecc703ae9697c3ac1380f61e741a3e1305f9499a2ddeba28149d77f39cc576e2da42a017

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
