---
hln: 6
msnbc: 7
dis_jr: 40
nick_jr: 41
sprout: 42
dis: 43
dis_xd: 44
nick: 45
free_form: 46
a_&_e: 47
usa: 48
tnt: 49
fx: 50
fxx: 51
syfy: 52
spike: 53
bbc: 54
amc: 55
tbs: 56
com: 57
ifc: 58
id: 59
tru: 60
disc_velocity: 61
disc: 62
science: 63
ani: 64
nat_geo: 65
nat_geo_wild: 66
hist: 67
viceland: 68
ahc: 69
food: 70
cooking: 71
travel: 72
hgtv: 73
diy: 74
lifetime: 75
lmn: 76
hallmark: 77
we_tv: 78
tv_land: 79
gsn: 80
tlc: 81
bravo: 82
own: 83
oxy: 84
e: 85
sundance: 86
mtv: 87
vh1: 88
bet: 89
mtv_live: 90
nbc_uni: 91
movie_plex: 92
tcm: 93
starz_encore: 94
starz_action: 95
starz_fam: 96
starz_suspense: 97
starz_black: 98
starz_esp: 99
showtime: 100
showtime2: 101
show_beyond: 102
showcase: 103
show_extreme: 104
showtime_women: 105
showtime_fam: 106
showtime_next: 107
starz: 108
starz_edge: 109
starz_in_black: 110
starz_kids_and_fam: 111
starz_cinema: 112
starz_comedy: 113
